from pathlib import Path

NOT_ON_CURRENT_PAGE_STR = "NotOnCurrentPage"
BOUNDARY_OF_SCOPE_STR = "Boundary-"
DEAD_END_STR = "DeadEnd-"
GO_SINK_STR = "GoSink"
STAY_SINK_STR = "StaySink"
INTERACTION_INTERCEPTED_STR = "InteractionIntercepted"
NOT_INTERACTABLE_STR = "NotInteractable"
outputs_without_page_change = [NOT_ON_CURRENT_PAGE_STR, BOUNDARY_OF_SCOPE_STR, DEAD_END_STR, GO_SINK_STR, STAY_SINK_STR,
                               INTERACTION_INTERCEPTED_STR, NOT_INTERACTABLE_STR]
SEPARATOR_BASIC = "-----------------------------------"
SEPARATOR_NEWLINE = "-----------------------------------\n"
DELIMITER_FOR_LETTER = ";"
SLASH = "/"
SLASH_REPLACEMENT = "|"

INPUT_ALPHABET_FILE_NAME = "input_alphabet.txt"
SCOPE_FILE_NAME = "scope.txt"
SCOPE_BOUNDARY_FILE_NAME = "scope_boundary.txt"
LOG_FILE_NAME = "log.txt"
INPUT_TRACES_FILE_NAME = "input_traces.txt"
IO_TRACES_FILE_NAME = "io_traces.txt"
AUTOMATON_TO_LEARN_FILE_NAME = "automaton_to_learn.dot"

RESULTS_DIRECTORY_NAME = "Results"
MODEL_DIRECTORY_NAME = "LearnedModels"
LEARNED_MODEL_FILE_NAME = "LM"

WITH_SELF_LOOPS_STR = "_withSL"
NO_SELF_LOOPS_STR = "_noSL"
ORIGINAL_STR = "_orig"
CLEAN_STR = "_clean"

RESULTS_DIR = Path(RESULTS_DIRECTORY_NAME)
MODEL_DIR = RESULTS_DIR / MODEL_DIRECTORY_NAME

PATH_LM_ORIG_NO_SL = MODEL_DIR / f"{LEARNED_MODEL_FILE_NAME}{ORIGINAL_STR}{NO_SELF_LOOPS_STR}"
PATH_LM_ORIG_WITH_SL = MODEL_DIR / f"{LEARNED_MODEL_FILE_NAME}{ORIGINAL_STR}{WITH_SELF_LOOPS_STR}"
PATH_LM_CLEAN_NO_SL = MODEL_DIR / f"{LEARNED_MODEL_FILE_NAME}{CLEAN_STR}{NO_SELF_LOOPS_STR}"
PATH_LM_CLEAN_WITH_SL = MODEL_DIR / f"{LEARNED_MODEL_FILE_NAME}{CLEAN_STR}{WITH_SELF_LOOPS_STR}"

PATH_INPUT_ALPHABET = RESULTS_DIR / INPUT_ALPHABET_FILE_NAME
PATH_SCOPE = RESULTS_DIR / SCOPE_FILE_NAME
PATH_SCOPE_BOUNDARY = RESULTS_DIR / SCOPE_BOUNDARY_FILE_NAME
PATH_LOG = RESULTS_DIR / LOG_FILE_NAME
PATH_INPUT_TRACES = RESULTS_DIR / INPUT_TRACES_FILE_NAME
PATH_IO_TRACES = RESULTS_DIR / IO_TRACES_FILE_NAME
