from enum import Enum


class ElementType(Enum):
    HREF = 1
    ONCLICK = 2
    ONCHANGE = 3
    ONMOUSEENTER = 4
    ONMOUSEOVER = 5
    ONMOUSELEAVE = 6
    ONMOUSEOUT = 7


class InteractionType(Enum):
    CLICK = 1
    SELECT_OPTION = 2
    START_HOVER = 3
    END_HOVER = 4


class EqOracleType(Enum):
    STATE_PREFIX = "STATE_PREFIX"
    RANDOM_WALK = "RANDOM_WALK"


class InputEnabledHandling(Enum):
    SELF_LOOP = "SELF_LOOP"
    SINK_STATE = "SINK_STATE"


class LearningType(Enum):
    ACTIVE = "ACTIVE"
    PASSIVE = "PASSIVE"


class SystemSource(Enum):
    FROM_BROWSER = "FROM_BROWSER"
    FROM_AUTOMATON_FILE = "FROM_AUTOMATON_FILE"  # used for testing and debugging only


class PassiveApproach(Enum):
    PTA_PREPROCESSING = "PTA_PREPROCESSING"
    COMPATIBILITY_FUNC = "COMPATIBILITY_FUNC"


class DemoWebsite(Enum):
    TEST_WEBSITE = "TEST_WEBSITE"
    TEST_WEBSITE_INDEX = "TW_INDEX"
    TEST_WEBSITE_BASICS = "TW_BASICS"
    TEST_WEBSITE_MAP_AREAS = "TW_MAP_AREAS"
    TEST_WEBSITE_DROPDOWNS = "TW_DROPDOWNS"
    TEST_WEBSITE_CHECKBOXES = "TW_CHECKBOXES"
    TEST_WEBSITE_SELECTIONS_CHOICES = "TW_SELECTIONS_CHOICES"
    TEST_WEBSITE_ATTRIBUTE_COMBINATIONS = "TW_ATTRIBUTE_COMBINATIONS"
    TEST_WEBSITE_TABS_WINDOWS = "TW_TABS_WINDOWS"
    OUTPUT_EXAMPLE = "OUTPUT_EXAMPLE"
    RUNNING_EXAMPLE = "RUNNING_EXAMPLE"
    HOVER_EXAMPLE = "HOVER_EXAMPLE"
    MOVING_ELEMENTS_EXAMPLE = "MOVING_ELEMENTS_EXAMPLE"
    CAR_ALARM = "CAR_ALARM"
