replacement_input_strings = {
    # ATTENTION: substrings of other strings should be listed last!

    # Test Website
    "https:||lklamb.github.io|Test_Website|index.html": "INDEX",
    "https:||lklamb.github.io|Test_Website|page1.html": "PAGE1",
    "https:||lklamb.github.io|Test_Website|page2.html": "PAGE2",
    "https:||lklamb.github.io|Test_Website|page3.html": "PAGE3",
    "https:||lklamb.github.io|Test_Website|page4.html": "PAGE4",
    "https:||lklamb.github.io|Test_Website|page5.html": "PAGE5",
    "https:||lklamb.github.io|Test_Website|basics.html": "BASICS",
    "https:||lklamb.github.io|Test_Website|map_areas.html": "MAP",
    "https:||lklamb.github.io|Test_Website|dropdowns.html": "DDOWNS",
    "https:||lklamb.github.io|Test_Website|checkboxes.html": "CBOXES",
    "https:||lklamb.github.io|Test_Website|selections_choices.html": "CHOICES",
    "https:||lklamb.github.io|Test_Website|attribute_combinations.html": "COMBI",
    "https:||lklamb.github.io|Test_Website|tabs_windows.html": "TABS",
    "https:||lklamb.github.io|Test_Website|empty.html": "EMPTY",
    "https:||lklamb.github.io|Test_Website|output-example_page1.html": "PAGE1",
    "https:||lklamb.github.io|Test_Website|output-example_page2.html": "PAGE2",
    "https:||lklamb.github.io|Test_Website|output-example_page3.html": "PAGE3",
    "https:||lklamb.github.io|Test_Website|output-example_page4.html": "PAGE4",
    "https:||lklamb.github.io|Test_Website|hover-example_page1.html": "PAGE1",
    "https:||lklamb.github.io|Test_Website|hover-example_page2.html": "PAGE2",
    "https:||lklamb.github.io|Test_Website|hover-example_page3.html": "PAGE3",
    "https:||lklamb.github.io|Test_Website|moving-elements-example_page1.html": "PAGE1",
    "https:||lklamb.github.io|Test_Website|moving-elements-example_page2.html": "PAGE2",
    "https:||lklamb.github.io|Test_Website|moving-elements-example_page3.html": "PAGE3",
    "https:||lklamb.github.io|Test_Website|running-example_page1.html": "PAGE1",
    "https:||lklamb.github.io|Test_Website|running-example_page2.html": "PAGE2",
    "https:||lklamb.github.io|Test_Website|running-example_page3.html": "PAGE3",
    "https:||lklamb.github.io|Test_Website|": "MAIN",
    "https:||example.com|": "EXAMPLE",

    # Car Alarm Demo Website (reduced version)
    "https:||lklamb.github.io|CarAlarmSystem_Demo|index.html;ONCLICK;0;front_right_door;CLICK": "NORMAL;front_right_door",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|armed.html;ONCLICK;0;front_right_door;CLICK": "ARMED;front_right_door",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|alarm.html;ONCLICK;0;front_right_door;CLICK": "ALARM;front_right_door",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|index.html;ONCLICK;1;LockUnlock;CLICK": "NORMAL;lock_unlock",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|armed.html;ONCLICK;1;LockUnlock;CLICK": "ARMED;lock_unlock",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|alarm.html;ONCLICK;1;LockUnlock;CLICK": "ALARM;lock_unlock",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|index.html;ONCLICK;2;Tick 10;CLICK": "NORMAL;tick_10",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|armed.html;ONCLICK;2;Tick 10;CLICK": "ARMED;tick_10",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|alarm.html;ONCLICK;2;Tick 10;CLICK": "ALARM;tick_10",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|index.html;HREF;0;Noun Project;CLICK": "NORMAL;noun-project",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|armed.html;HREF;0;Noun Project;CLICK": "ARMED;noun-project",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|alarm.html;HREF;0;Noun Project;CLICK": "ALARM;noun-project",
    }

replacement_output_strings = {
    # ATTENTION: substrings of other strings should be listed last!

    # Test Website
    "https:||lklamb.github.io|Test_Website|index.html": "INDEX",
    "https:||lklamb.github.io|Test_Website|page1.html": "PAGE1",
    "https:||lklamb.github.io|Test_Website|page2.html": "PAGE2",
    "https:||lklamb.github.io|Test_Website|page3.html": "PAGE3",
    "https:||lklamb.github.io|Test_Website|page4.html": "PAGE4",
    "https:||lklamb.github.io|Test_Website|page5.html": "PAGE5",
    "https:||lklamb.github.io|Test_Website|basics.html": "BASICS",
    "https:||lklamb.github.io|Test_Website|map_areas.html": "MAP",
    "https:||lklamb.github.io|Test_Website|dropdowns.html": "DDOWNS",
    "https:||lklamb.github.io|Test_Website|checkboxes.html": "CBOXES",
    "https:||lklamb.github.io|Test_Website|selections_choices.html": "CHOICES",
    "https:||lklamb.github.io|Test_Website|attribute_combinations.html": "COMBI",
    "https:||lklamb.github.io|Test_Website|tabs_windows.html": "TABS",
    "https:||lklamb.github.io|Test_Website|empty.html": "EMPTY",
    "https:||lklamb.github.io|Test_Website|output-example_page1.html": "PAGE1",
    "https:||lklamb.github.io|Test_Website|output-example_page2.html": "PAGE2",
    "https:||lklamb.github.io|Test_Website|output-example_page3.html": "PAGE3",
    "https:||lklamb.github.io|Test_Website|output-example_page4.html": "PAGE4",
    "https:||lklamb.github.io|Test_Website|hover-example_page1.html": "PAGE1",
    "https:||lklamb.github.io|Test_Website|hover-example_page2.html": "PAGE2",
    "https:||lklamb.github.io|Test_Website|hover-example_page3.html": "PAGE3",
    "https:||lklamb.github.io|Test_Website|moving-elements-example_page1.html": "PAGE1",
    "https:||lklamb.github.io|Test_Website|moving-elements-example_page2.html": "PAGE2",
    "https:||lklamb.github.io|Test_Website|moving-elements-example_page3.html": "PAGE3",
    "https:||lklamb.github.io|Test_Website|running-example_page1.html": "PAGE1",
    "https:||lklamb.github.io|Test_Website|running-example_page2.html": "PAGE2",
    "https:||lklamb.github.io|Test_Website|running-example_page3.html": "PAGE3",
    "https:||lklamb.github.io|Test_Website|": "MAIN",
    "https:||example.com|": "EXAMPLE",

    # Car Alarm Demo Website
    "https:||lklamb.github.io|CarAlarmSystem_Demo|index.html": "NORMAL",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|armed.html": "ARMED",
    "https:||lklamb.github.io|CarAlarmSystem_Demo|alarm.html": "ALARM",
    "https:||thenounproject.com|browse|collection-icon|auto-parts-5386|?p=1": "NOUN-PROJECT",

}